POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "league of legends2",
  "author": "phreak2",
  "url": "abcd",
  "likes": 100,
	"userId": "628d239b533f0022664d85b4"
}

###

DELETE http://localhost:3003/api/blogs/62957843ef1b9063548e11bb

###

PUT http://localhost:3003/api/blogs/62671a8091aaa44f01c6e729
Content-Type: application/json

{
  "likes": 77
}