POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "myko",
  "number": "647-123-1234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "binds",
  "number": "369-369-9999"
}

###

DELETE http://localhost:3001/api/persons/62570a9e23466d639056ddf2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

###

GET http://localhost:3001/api/persons/6257425fe60096c164301c36


